# version: '3'

services:
  web:
    build: ./inventory_project
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./inventory_project:/code
    ports:
      - "8000:8000"

